{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "tentacular-mcp.namespace" . }}
  labels:
    {{- include "tentacular-mcp.labels" . | nindent 4 }}
{{- end }}
